docs: commands/interactions support chinese
testerhome/appium pull request #11
Opened 2020-07-17 14:04 UTC by TracyYaoYao

## Proposed changes

docs: commands/interactions support chinese version.

2020-07-18 16:09 UTC, lihuazhang requested changes

2020-07-18 16:09 UTC, lihuazhang commented on docs/cn/commands/interactions/actions.md
> +执行一个或多个键盘和指针（触摸、鼠标、手写笔）操作
键盘和触控操作

2020-07-28 04:04 UTC, TracyYaoYao commented on docs/cn/commands/interactions/actions.md
> +执行一个或多个键盘和指针（触摸、鼠标、手写笔）操作
感谢指正！已经修改

2020-08-08 09:42 UTC, lihuazhang approved these changes

2020-08-08 09:42 UTC, merged