Chinese translation for swipe tutorial.
testerhome/appium pull request #19
Opened 2020-07-23 10:40 UTC by gebitang

## Proposed changes

Just add Chinese translation for swipe tutorial.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

2020-08-08 10:08 UTC, lihuazhang requested changes
翻译的挺不错的。有几个点你看看改一下。

2020-08-08 10:08 UTC, lihuazhang commented on docs/cn/writing-running-appium/tutorial/swipe/swipe-troubleshoot-guide.md
> +1. 是否需要使用请准swipe而不是scroll方法
是否需要使用请准swipe而不是scroll方法？看不懂

2020-08-08 10:08 UTC, lihuazhang commented on docs/cn/writing-running-appium/tutorial/swipe/ios-picker-wheels-set-value.md
> +不幸的是，XCTest不能总是很好地与轮式选择器控件(PickerWheel)进行交互。有时，setValue()方法调用可能没有任何效果。
不能总是===》总是不能 是不是好一点。你读一下看看？

2020-08-09 06:58 UTC, gebitang commented on docs/cn/writing-running-appium/tutorial/swipe/swipe-troubleshoot-guide.md
> +1. 是否需要使用请准swipe而不是scroll方法
If you need precise swipe prefer scroll method. 

修改为“尝试使用精准swipe而不是scroll方法”

请准 是个 拼写错误

2020-08-09 06:59 UTC, gebitang commented on docs/cn/writing-running-appium/tutorial/swipe/ios-picker-wheels-set-value.md
> +不幸的是，XCTest不能总是很好地与轮式选择器控件(PickerWheel)进行交互。有时，setValue()方法调用可能没有任何效果。
不能总是：大部分情况OK，少部分情况不OK

总是不能：大部分情况都不OK

2020-08-23 06:40 UTC, merged