add CN documents in docs/cn/commands/device/activity/
testerhome/appium pull request #2
Opened 2020-07-09 06:25 UTC by KangarooChen

## Proposed changes

add CN documents

## Types of changes

What types of changes does your code introduce to Appium?

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

2020-07-09 12:59 UTC, lihuazhang approved these changes

2020-07-09 13:02 UTC, lihuazhang requested changes
Activity 是专业术语，不要翻译。

2020-07-10 01:31 UTC, KangarooChen reviewed
revert some proper nouns translation

2020-07-10 01:33 UTC, KangarooChen commented
已修改

2020-07-10 06:05 UTC, lihuazhang approved these changes

2020-07-10 06:05 UTC, merged