docs/cn/writing-running-appium/ios/ios-xctest-mobile-gestures.md
testerhome/appium pull request #20
Opened 2020-07-25 08:51 UTC by jiyirain

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-07-25 09:12 UTC, jiyirain commented
└── writing-running-appium
├── ios
│ ├── ios-xctest-mobile-gestures.md
│ ├── ios-xctest-pasteboard.md
│ └── ios-xctest-performance.md

2020-08-08 10:02 UTC, lihuazhang requested changes

2020-08-08 10:02 UTC, lihuazhang commented on docs/cn/writing-running-appium/ios/ios-xctest-mobile-gestures.md
> + 从Appium 1.17.1.以来，对于一个或多个接触点发送一次或多次的点击操作
从Appium 1.17.1.以来 ==》 从Appium 1.17.1 开始。

Sends one or more taps with one or more touch points since Appium 1.17.1.

原句最后的一个.是句号。

从Appium 1.17.1 开始，对单个或者多个触碰点，点击一次或者多次。

2020-08-08 10:02 UTC, lihuazhang commented on docs/cn/writing-running-appium/ios/ios-xctest-mobile-gestures.md
> + * _element_: 执行一次或多次的内部元素控件ID（作为十六进制哈希字符串
右括号呢？翻译的也不太对

2020-09-01 15:48 UTC, lihuazhang approved these changes

2020-09-01 15:49 UTC, merged