driver-translate-chinese
testerhome/appium pull request #27
Opened 2020-07-28 09:40 UTC by TracyYaoYao

## Proposed changes
driver-translate-chinese

2020-08-08 09:36 UTC, lihuazhang requested changes
麻烦重新校对下，翻译太生硬，错误较多。别用百度翻译或者谷歌翻译。

2020-08-08 09:36 UTC, lihuazhang commented on docs/cn/drivers/android-espresso.md
> +Appium目前通过自己的Espresso驱动程序支持[Espresso](https://developer.android.com/training/testing/espresso/index.html)自动化技术。这个驱动程序通过启动设备上运行的Espresso来工作，并将我们自己的自动化服务器作为Espresso测试APK的一部分。在此基础上，Appium可以与此自动化服务器进行通信，
驱动程序 还是用 driver 吧

2020-08-12 08:42 UTC, TracyYaoYao commented on docs/cn/drivers/android-espresso.md
> +Appium目前通过自己的Espresso驱动程序支持[Espresso](https://developer.android.com/training/testing/espresso/index.html)自动化技术。这个驱动程序通过启动设备上运行的Espresso来工作，并将我们自己的自动化服务器作为Espresso测试APK的一部分。在此基础上，Appium可以与此自动化服务器进行通信，
好的 谢谢

2020-09-01 02:10 UTC, TracyYaoYao commented
@lihuazhang 已经更新，麻烦再review一下。

2020-09-01 15:43 UTC, lihuazhang requested changes
你翻译的时候，要读读看，通不通呀。

2020-09-01 15:43 UTC, lihuazhang commented on docs/cn/drivers/android-espresso.md
> +在[appium-espresso-driver](https://github.com/appium/appium-espresso-driver)的回购了Espresso driver后，该driver开始发展。
啥是回购啊？

2020-09-01 15:43 UTC, lihuazhang commented on docs/cn/drivers/android-uiautomator2.md
> +此外，UiAutomator2 driver不支持低于5.0的Android版本（Lollipop，API级别21）。如果要自动执行这一类的版本，请考虑使用 [UiAutomator驱动](/docs/en/drivers/android-uiautomator.md)。
用cn的目录

2020-09-12 06:13 UTC, merged