contributing-to-appium和advanced-concepts部分
testerhome/appium pull request #28
Opened 2020-08-02 16:54 UTC by nicole1010

简略修改说明：
├── advanced-concepts
│ ├── migrating-to-xcuitest.md -> 删除部分英文原文，修改少量不通顺部分，更新已知问题-done
│ ├── multiple-xcode-versions.md -> 新增文件-done
│ ├── parallel-tests.md -> Android部分更新，iOS完全改变-done
│ ├── settings.md -> Android/iOS增加一堆-done
│ └── wda-custom-server.md -> 更新部分新增内容-done

├── contributing-to-appium
│ ├── appium-from-source.md -> 少量语序调整，新增node部分-done
│ ├── appium-packages.md -> 少量更改-done
│ ├── appium-packages.png -> 图片
│ ├── dev-tools.md -> 新文件-done
│ ├── developers-overview.md -> 部分新增文本-done
│ ├── real-device-ci.md -> 新文件-done
│ ├── style-guide.md -> 新增JS部分、Linting部分删减更新、大部分js语句替换-done
│ └── version-branch-release.md -> 无更新

└── writing-running-appium
├── ios
│ ├── ios-predicate.md -> 新增了3句-done
│ ├── ios-touch-id.md -> 无更新

2020-08-08 09:31 UTC, lihuazhang requested changes

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/multiple-xcode-versions.md
> +如果安装了多个 Xcode，则需要选择 Appium 需要使用的工具集，可以从以下2中方法里选一个：
如果安装了多个 Xcode，则需要选择 Appium 需要使用的工具集，可以从以下2中方法里选一个：

如果你的电脑上安装了多个 Xcode，你可能需要从以下2种方法里选一个工具集供 Appium 使用。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/multiple-xcode-versions.md
> +仅 sudo 权限可用，影响整个系统。
仅 sudo 权限可用，会影响整个系统。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/parallel-tests.md
> +Appium 给用户提供了在一个机器、一个服务服务实例上启动多个 Android sessions 的方案。可以使用任意可用端口启动 Appium 服务
给用户提供了在单机上启动多个 Android sessions 的方案。

on a single machine on single server instance 看上去有点啰嗦了。翻译成单机是不是语义就够了？

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/parallel-tests.md
> +注意，在 *同一设备上* 不能运行 多个 session.
注意，在 *同一设备上* 不能运行多个 session.

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/parallel-tests.md
> +如果在一个测试 job里使用大量模拟器，当第一个测试结束，Jenkins 可能会 kill 掉所有模拟器，这会导致 剩下的测试 jobs 报错！
翻译里的面的空格逻辑很奇怪啊，一般英文前后加空格就可以了。你修复下。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +本文由 [ghost62184](https://github.com/ghost62184) 翻译， 由 [chenhengjie123](https://github.com/chenhengjie123) 校验
两个本文翻译，校验，删掉一个？

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +| `ignoreUnimportantViews` | 设置为false时，Android设备不会忽略任何视图；被设置为true时，会使用setCompressedLayoutHeirarchy()忽略标记了IMPORTANT_FOR_ACCESSIBILITY_NO或IMPORTANT_FOR_ACCESSIBILITY_AUTO（以及被系统认为不重要的）的视图，从而尽量让脚本变得简单或执行
视图，还是保留英文吧。使用视图看不懂。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +| `wakeLockTimeout` | 获取唤醒锁（wake lock）超时时间。服务启动时获取并持有唤醒锁（wake lock），直到 UIAutomator2 服务被杀掉或者超时过期。唤醒锁（wake lock）被持有时，如果设置值为0或负数，将会立即被释放。默认值为 '24 * 60 * 60 * 1000' 毫秒。 | 例如 `0`, `60000` (1 min) |
超时过期 不就是超时么。。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +|`nativeWebTap`| 启用后,可以在 Safari 里点击 non-javascript-based 页面。默认值为 `false`，提醒：依赖视窗（viewport）的大小/比例，点击元素时可能不太准确。 | `true`, `false` |1.7.0+|
依赖视窗（viewport）还是不用翻译。。英文更加标准。

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +|`reduceMotion`| 在辅助功能里修改"减弱动态效果"。 | `true`, `false` |1.15.0+|
减弱动态效果 这个加个英文注释比如。

减弱动态效果(motion)

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +| `includeNonModalElements` | iOS 13+ 设备上，是否返回所有带对话框的元素。这个设置解决了这个问题[cannot find elements on nested modal presentations](https://github.com/appium/appium/issues/13227),但也会导致可见属性不可靠。为了提升元素可见监测，还要开启 `sh
逗号统一一下，不要一会儿英文的逗号，一会儿中文的逗号

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/settings.md
> +| `includeNonModalElements` | iOS 13+ 设备上，是否返回所有带对话框的元素。这个设置解决了这个问题[cannot find elements on nested modal presentations](https://github.com/appium/appium/issues/13227),但也会导致可见属性不可靠。为了提升元素可见监测，还要开启 `sh
句号也一样，全文统一扫描下吧

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/wda-custom-server.md
> + * 即便 xcodebuild 和 iproxy 进程已经被冻结，我们在重新启动之前杀死这些进程，以确保编译成功，
* 就算 xcodebuild 和 iproxy 进程已经被冻结，我们在重新启动之前杀死这些进程，也可以确保编译成功

2020-08-08 09:31 UTC, lihuazhang commented on docs/cn/advanced-concepts/wda-custom-server.md
> +本文由 [simple](https://testerhome.com/simple) 翻译，由 [lihuazhang](https://github.com/lihuazhang) 校验。
删除

2020-08-17 07:32 UTC, nicole1010 commented
根据上述修改意见，本地修改后重新提交
感谢指导，辛苦啦

主要为以下3类修改：
1、翻译后的文本调整
2、标点符号统一，逗号和句号
3、空格，调整为中英文句子里，英文前后加空格（去掉纯中文句子，前缀空格）

2020-08-23 06:41 UTC, merged