新增about-appium/getting-started.md翻译
testerhome/appium pull request #4
Opened 2020-07-13 04:40 UTC by XiufanJi

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-07-18 15:28 UTC, lihuazhang requested changes

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +本篇文章将会带你了解并运行一个简单的appium案例以及向你介绍一些关于appium的基本概念。想要了解更多关于appium的详细信息，请查看[相关介绍](/docs/en/about-appium/intro.md)。
这里的相关介绍也是跳转到英文文档的，可以link去中文的文档吧？

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +如果你想使用`npm install`命令进行appium的安装，hack操作或者是为appium做贡献，你都需要安装[Node.js和NPM](http://nodejs.org)（使用[nvm](https://github.com/creationix/nvm),[n](https://github.com/visionmedia/n)命令，或者是`brew install node`命令
如果你想使用`npm install`命令进行appium的安装，hack操作或者是为appium做贡献
建议改成

如果你想用 `npm install`命令安装appium，或者改造appium，或者向appium提交代码做贡献

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +- [Mac 驱动](/docs/en/drivers/mac.md) (Mac操作系统桌面应用使用)
driver 不需要翻译，翻译了反而难理解。
iOS 不是 IOS，这个要专业一点。

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +尽管如此，正如移动端可以进行的某些操作不能在浏览器端进行，有些操作也是Appium可以但是Selenium却不行。因此，为了弥补这些不足，我们在传统Selenium客户端已有功能的基础上进行了相应的扩展，提供了一系列支持不同编程语言的Appium客户端。你可通过查看[Appium客户端列表](/docs/en/about-appium/appium-clients.md)页面，点击相应的链接进行
你可通过查看[Appium客户端列表](/docs/en/about-appium/appium-clients.md)页面，

提供中文的地址

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +- [命令相关](https://appium.io/docs/en/commands/status/) - 学习可用的命令，如何将它们与特定的客户端进行使用等...
这里也应该用中文文档的地址

2020-07-18 15:28 UTC, lihuazhang commented on docs/cn/about-appium/getting-started.md
> +在该部分，我们将会运行一个简单的“Hello World”安卓测试用例。之所以选择安卓是因为它在所有平台上都能运行。同时，我们将使用[UiAutomator2 驱动](/docs/en/drivers/android-uiautomator2.md)，所以请确保你已经通读过相关文档并且系统已经具备所需的环境。本次将使用JavaScript作为开发语言，以便于不需要再使用到其他的依赖组件。
同时，我们将使用[UiAutomator2 驱动](/docs/en/drivers/android-uiautomator2.md) 一样要用中文文档

2020-07-19 14:02 UTC, XiufanJi commented
多谢指正，后续会更加的仔细一点，前面提出问题的地方都已修改提交

2020-08-08 09:38 UTC, lihuazhang approved these changes

2020-08-08 09:38 UTC, merged