翻译了 commands/web/execute.md
testerhome/appium pull request #5
Opened 2020-07-13 08:59 UTC by zhengjiani

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-07-18 15:47 UTC, lihuazhang requested changes

2020-07-18 15:47 UTC, lihuazhang commented on docs/cn/commands/web/execute.md
> +参数可以是任何JSON原语, 数组, 或者 JSON 对象。 定义WebElement引用的JSON对象将转换为相应的DOM元素。 同样地, 脚本结果中的任何WebElements都将作为WebElement JSON对象返回给客户端。
JSON-primitive 翻译成 JSON原语, 这个应该是 JSON 的基本类型

2020-07-18 15:47 UTC, lihuazhang commented on docs/cn/commands/web/execute.md
> +原生上下文（Native Context）中 `execute` , 详见 [Mobile Commands](/docs/en/commands/mobile-command.md).
native context 这个就别翻译了

2020-07-18 15:47 UTC, lihuazhang commented on docs/cn/commands/web/execute.md
> +|语言|支持|文档|
支持是支持的什么？

2020-07-18 15:47 UTC, lihuazhang commented on docs/cn/commands/web/navigation/url.md
> +检索当前页面的URL (仅是 Web context)
获取当前页面的URL

2020-07-19 05:25 UTC, zhengjiani commented on docs/cn/commands/web/navigation/url.md
> +检索当前页面的URL (仅是 Web context)
已全部做修改，谢谢指导～

2020-07-20 12:09 UTC, lihuazhang requested changes

2020-07-20 12:09 UTC, lihuazhang commented on docs/cn/commands/web/frame/switch.md
> +将焦点更改为页面上的另一个框架 (仅是 Web context)
frame 还是不要翻译成框架吧？

你搜索下，所有的frame，还是用frame吧，框架理解不了。大部分地方都不翻译这个字的

2020-07-20 12:09 UTC, lihuazhang commented on docs/cn/commands/web/navigation/back.md
> +如果可以，向后导航浏览器历史记录 (仅是 Web context)
这句看不太懂，能不能调整下？比较顺口一点？

2020-07-20 12:09 UTC, lihuazhang commented on docs/cn/commands/web/navigation/forward.md
> +如果可以，向前导航浏览器历史记录 (仅是 Web context)
这句也是，不能对着词语翻译，组织下中文语句。

2020-07-27 14:16 UTC, zhengjiani commented on docs/cn/commands/web/navigation/forward.md
> +如果可以，向前导航浏览器历史记录 (仅是 Web context)
已修改+新提交，麻烦review～

2020-08-08 09:41 UTC, lihuazhang approved these changes

2020-08-08 09:41 UTC, lihuazhang commented on docs/cn/commands/web/frame/parent.md
> +如果当前上下文是顶级浏览上下文, 则上下文保持不变。
顶级浏览上下文 这个看不太懂诶

2020-08-08 09:41 UTC, merged