add CN documents in docs/cn/commands/device/app
testerhome/appium pull request #6
Opened 2020-07-14 02:38 UTC by zhangfeng91

## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

## Types of changes

What types of changes does your code introduce to Appium?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [ ] I have read the [CONTRIBUTING](https://github.com/appium/appium/blob/master/CONTRIBUTING.md) doc
- [ ] I have signed the [CLA](https://cla.js.foundation/appium/appium)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

2020-07-18 16:24 UTC, lihuazhang requested changes

2020-07-18 16:24 UTC, lihuazhang commented on docs/cn/commands/device/app/install-app.md
> +|语言|支持|文档|
支持啥？

2020-07-18 16:24 UTC, lihuazhang commented on docs/cn/commands/device/app/remove-app.md
> +使用XCUITest的iOS测试也可以使用“ mobile：removeApp”方法。 详见 [文档]](/docs/cn/writing-running-appium/ios/ios-xctest-mobile-apps-management.md#mobile-removeapp).
同上

2020-07-19 08:12 UTC, zhangfeng91 commented on docs/cn/commands/device/app/install-app.md
> +|语言|支持|文档|
已修改

2020-07-20 12:02 UTC, lihuazhang approved these changes

2020-07-20 12:02 UTC, merged