update contributing-to-appium&writing-running-appium
testerhome/appium pull request #7
Opened 2020-07-14 02:46 UTC by purviszhang

update
```
├── contributing-to-appium
│   ├── credits.md
│   ├── how-to-write-docs.md
```
```
── writing-running-appium
    ├── caps.md
    ├── default-capabilities-arg.md
    ├── finding-elements.md
```
TesterHome 社区 id：haliOrange

2020-07-18 16:18 UTC, lihuazhang requested changes

2020-07-18 16:18 UTC, lihuazhang commented on docs/cn/writing-running-appium/finding-elements.md
>  * `accessibility id`：该字符串相当于利用原生的可访问性（Accessibility）选项，使用 Id / Name 去递归地搜索元素。
得用cn啊

2020-07-20 09:05 UTC, purviszhang commented
已修改
TesterHome 社区 id：haliOrange

2020-07-20 09:12 UTC, purviszhang commented on docs/cn/writing-running-appium/finding-elements.md
>  * `accessibility id`：该字符串相当于利用原生的可访问性（Accessibility）选项，使用 Id / Name 去递归地搜索元素。
已修改

2020-07-20 12:11 UTC, lihuazhang approved these changes

2020-07-20 12:11 UTC, merged